// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: orm.proto

package orm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Type int32

const (
	Type_TYPE_UNSPECIFIED Type = 0
	Type_TYPE_BOOL        Type = 8
	Type_TYPE_ENUM        Type = 14
	Type_TYPE_INT32       Type = 5
	Type_TYPE_SINT32      Type = 17
	Type_TYPE_UINT32      Type = 13
	Type_TYPE_INT64       Type = 3
	Type_TYPE_SINT64      Type = 18
	Type_TYPE_UINT64      Type = 4
	Type_TYPE_SFIXED32    Type = 15
	Type_TYPE_FIXED32     Type = 7
	Type_TYPE_FLOAT       Type = 2
	Type_TYPE_SFIXED64    Type = 16
	Type_TYPE_FIXED64     Type = 6
	Type_TYPE_DOUBLE      Type = 1
	Type_TYPE_STRING      Type = 9
	Type_TYPE_BYTES       Type = 12
	Type_TYPE_MESSAGE     Type = 11
	Type_TYPE_GROUP       Type = 10
	Type_TYPE_INT         Type = 3 // int decay.
	Type_TYPE_UINT        Type = 4 // unsigned int decay.
	Type_TYPE_UUID        Type = 64
	Type_TYPE_TIME        Type = 65
	Type_TYPE_JSON        Type = 66
)

// Enum value maps for Type.
var (
	Type_name = map[int32]string{
		0:  "TYPE_UNSPECIFIED",
		8:  "TYPE_BOOL",
		14: "TYPE_ENUM",
		5:  "TYPE_INT32",
		17: "TYPE_SINT32",
		13: "TYPE_UINT32",
		3:  "TYPE_INT64",
		18: "TYPE_SINT64",
		4:  "TYPE_UINT64",
		15: "TYPE_SFIXED32",
		7:  "TYPE_FIXED32",
		2:  "TYPE_FLOAT",
		16: "TYPE_SFIXED64",
		6:  "TYPE_FIXED64",
		1:  "TYPE_DOUBLE",
		9:  "TYPE_STRING",
		12: "TYPE_BYTES",
		11: "TYPE_MESSAGE",
		10: "TYPE_GROUP",
		// Duplicate value: 3: "TYPE_INT",
		// Duplicate value: 4: "TYPE_UINT",
		64: "TYPE_UUID",
		65: "TYPE_TIME",
		66: "TYPE_JSON",
	}
	Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"TYPE_BOOL":        8,
		"TYPE_ENUM":        14,
		"TYPE_INT32":       5,
		"TYPE_SINT32":      17,
		"TYPE_UINT32":      13,
		"TYPE_INT64":       3,
		"TYPE_SINT64":      18,
		"TYPE_UINT64":      4,
		"TYPE_SFIXED32":    15,
		"TYPE_FIXED32":     7,
		"TYPE_FLOAT":       2,
		"TYPE_SFIXED64":    16,
		"TYPE_FIXED64":     6,
		"TYPE_DOUBLE":      1,
		"TYPE_STRING":      9,
		"TYPE_BYTES":       12,
		"TYPE_MESSAGE":     11,
		"TYPE_GROUP":       10,
		"TYPE_INT":         3,
		"TYPE_UINT":        4,
		"TYPE_UUID":        64,
		"TYPE_TIME":        65,
		"TYPE_JSON":        66,
	}
)

func (x Type) Enum() *Type {
	p := new(Type)
	*p = x
	return p
}

func (x Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Type) Descriptor() protoreflect.EnumDescriptor {
	return file_orm_proto_enumTypes[0].Descriptor()
}

func (Type) Type() protoreflect.EnumType {
	return &file_orm_proto_enumTypes[0]
}

func (x Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Type.Descriptor instead.
func (Type) EnumDescriptor() ([]byte, []int) {
	return file_orm_proto_rawDescGZIP(), []int{0}
}

type FileOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      *FileMessageOptions    `protobuf:"bytes,1,opt,name=messages,proto3" json:"messages,omitempty"`
	Rpcs          *FileRpcOptions        `protobuf:"bytes,2,opt,name=rpcs,proto3" json:"rpcs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOptions) Reset() {
	*x = FileOptions{}
	mi := &file_orm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOptions) ProtoMessage() {}

func (x *FileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_orm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOptions.ProtoReflect.Descriptor instead.
func (*FileOptions) Descriptor() ([]byte, []int) {
	return file_orm_proto_rawDescGZIP(), []int{0}
}

func (x *FileOptions) GetMessages() *FileMessageOptions {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *FileOptions) GetRpcs() *FileRpcOptions {
	if x != nil {
		return x.Rpcs
	}
	return nil
}

type FileMessageOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disabled      bool                   `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileMessageOptions) Reset() {
	*x = FileMessageOptions{}
	mi := &file_orm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileMessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileMessageOptions) ProtoMessage() {}

func (x *FileMessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_orm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileMessageOptions.ProtoReflect.Descriptor instead.
func (*FileMessageOptions) Descriptor() ([]byte, []int) {
	return file_orm_proto_rawDescGZIP(), []int{1}
}

func (x *FileMessageOptions) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type MessageOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       *bool                  `protobuf:"varint,1,opt,name=enabled,proto3,oneof" json:"enabled,omitempty"`
	Indexes       []*Index               `protobuf:"bytes,2,rep,name=indexes,proto3" json:"indexes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	mi := &file_orm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_orm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_orm_proto_rawDescGZIP(), []int{2}
}

func (x *MessageOptions) GetEnabled() bool {
	if x != nil && x.Enabled != nil {
		return *x.Enabled
	}
	return false
}

func (x *MessageOptions) GetIndexes() []*Index {
	if x != nil {
		return x.Indexes
	}
	return nil
}

type FieldOptions struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Ignored   bool                   `protobuf:"varint,1,opt,name=ignored,proto3" json:"ignored,omitempty"`
	Type      Type                   `protobuf:"varint,2,opt,name=type,proto3,enum=orm.Type" json:"type,omitempty"`
	Key       bool                   `protobuf:"varint,5,opt,name=key,proto3" json:"key,omitempty"`
	Unique    bool                   `protobuf:"varint,6,opt,name=unique,proto3" json:"unique,omitempty"`
	Nullable  bool                   `protobuf:"varint,7,opt,name=nullable,proto3" json:"nullable,omitempty"`
	Immutable bool                   `protobuf:"varint,8,opt,name=immutable,proto3" json:"immutable,omitempty"`
	// Mark a field as optional for AddRequest message.
	// This is useful when a field is unique and therefore
	// cannot have a default value, but the server generates
	// the value, so you want to make the field optional for the user.
	Supplied      bool    `protobuf:"varint,10,opt,name=supplied,proto3" json:"supplied,omitempty"`
	Default       *string `protobuf:"bytes,9,opt,name=default,proto3,oneof" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldOptions) Reset() {
	*x = FieldOptions{}
	mi := &file_orm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldOptions) ProtoMessage() {}

func (x *FieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_orm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldOptions.ProtoReflect.Descriptor instead.
func (*FieldOptions) Descriptor() ([]byte, []int) {
	return file_orm_proto_rawDescGZIP(), []int{3}
}

func (x *FieldOptions) GetIgnored() bool {
	if x != nil {
		return x.Ignored
	}
	return false
}

func (x *FieldOptions) GetType() Type {
	if x != nil {
		return x.Type
	}
	return Type_TYPE_UNSPECIFIED
}

func (x *FieldOptions) GetKey() bool {
	if x != nil {
		return x.Key
	}
	return false
}

func (x *FieldOptions) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *FieldOptions) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *FieldOptions) GetImmutable() bool {
	if x != nil {
		return x.Immutable
	}
	return false
}

func (x *FieldOptions) GetSupplied() bool {
	if x != nil {
		return x.Supplied
	}
	return false
}

func (x *FieldOptions) GetDefault() string {
	if x != nil && x.Default != nil {
		return *x.Default
	}
	return ""
}

type EdgeOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ignored       bool                   `protobuf:"varint,1,opt,name=ignored,proto3" json:"ignored,omitempty"`
	Bind          int32                  `protobuf:"varint,2,opt,name=bind,proto3" json:"bind,omitempty"`
	From          *BackRefOptions        `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Nullable      bool                   `protobuf:"varint,7,opt,name=nullable,proto3" json:"nullable,omitempty"`
	Immutable     bool                   `protobuf:"varint,8,opt,name=immutable,proto3" json:"immutable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EdgeOptions) Reset() {
	*x = EdgeOptions{}
	mi := &file_orm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EdgeOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EdgeOptions) ProtoMessage() {}

func (x *EdgeOptions) ProtoReflect() protoreflect.Message {
	mi := &file_orm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EdgeOptions.ProtoReflect.Descriptor instead.
func (*EdgeOptions) Descriptor() ([]byte, []int) {
	return file_orm_proto_rawDescGZIP(), []int{4}
}

func (x *EdgeOptions) GetIgnored() bool {
	if x != nil {
		return x.Ignored
	}
	return false
}

func (x *EdgeOptions) GetBind() int32 {
	if x != nil {
		return x.Bind
	}
	return 0
}

func (x *EdgeOptions) GetFrom() *BackRefOptions {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *EdgeOptions) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *EdgeOptions) GetImmutable() bool {
	if x != nil {
		return x.Immutable
	}
	return false
}

type BackRefOptions struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Number int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	// Create virtual edge to this entity.
	// It is error if the edge already exist and this value is set.
	Virtual       *VirtualBackRefOptions `protobuf:"bytes,2,opt,name=virtual,proto3" json:"virtual,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackRefOptions) Reset() {
	*x = BackRefOptions{}
	mi := &file_orm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackRefOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackRefOptions) ProtoMessage() {}

func (x *BackRefOptions) ProtoReflect() protoreflect.Message {
	mi := &file_orm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackRefOptions.ProtoReflect.Descriptor instead.
func (*BackRefOptions) Descriptor() ([]byte, []int) {
	return file_orm_proto_rawDescGZIP(), []int{5}
}

func (x *BackRefOptions) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *BackRefOptions) GetVirtual() *VirtualBackRefOptions {
	if x != nil {
		return x.Virtual
	}
	return nil
}

type VirtualBackRefOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Default to entity name.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Shared        bool   `protobuf:"varint,2,opt,name=shared,proto3" json:"shared,omitempty"`
	Nullable      bool   `protobuf:"varint,7,opt,name=nullable,proto3" json:"nullable,omitempty"`
	Immutable     bool   `protobuf:"varint,8,opt,name=immutable,proto3" json:"immutable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VirtualBackRefOptions) Reset() {
	*x = VirtualBackRefOptions{}
	mi := &file_orm_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VirtualBackRefOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtualBackRefOptions) ProtoMessage() {}

func (x *VirtualBackRefOptions) ProtoReflect() protoreflect.Message {
	mi := &file_orm_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtualBackRefOptions.ProtoReflect.Descriptor instead.
func (*VirtualBackRefOptions) Descriptor() ([]byte, []int) {
	return file_orm_proto_rawDescGZIP(), []int{6}
}

func (x *VirtualBackRefOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtualBackRefOptions) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

func (x *VirtualBackRefOptions) GetNullable() bool {
	if x != nil {
		return x.Nullable
	}
	return false
}

func (x *VirtualBackRefOptions) GetImmutable() bool {
	if x != nil {
		return x.Immutable
	}
	return false
}

type SelectOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Select all fields if empty.
	Refs          []int32 `protobuf:"varint,2,rep,packed,name=refs,proto3" json:"refs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelectOptions) Reset() {
	*x = SelectOptions{}
	mi := &file_orm_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelectOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelectOptions) ProtoMessage() {}

func (x *SelectOptions) ProtoReflect() protoreflect.Message {
	mi := &file_orm_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelectOptions.ProtoReflect.Descriptor instead.
func (*SelectOptions) Descriptor() ([]byte, []int) {
	return file_orm_proto_rawDescGZIP(), []int{7}
}

func (x *SelectOptions) GetRefs() []int32 {
	if x != nil {
		return x.Refs
	}
	return nil
}

type FileRpcOptions struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Disabled bool                   `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// Enables add, get, patch, and erase.
	Crud          bool      `protobuf:"varint,2,opt,name=crud,proto3" json:"crud,omitempty"`
	Add           *RpcAdd   `protobuf:"bytes,16,opt,name=add,proto3,oneof" json:"add,omitempty"`
	Get           *RpcGet   `protobuf:"bytes,17,opt,name=get,proto3,oneof" json:"get,omitempty"`
	List          *RpcList  `protobuf:"bytes,18,opt,name=list,proto3,oneof" json:"list,omitempty"`
	Patch         *RpcPatch `protobuf:"bytes,19,opt,name=patch,proto3,oneof" json:"patch,omitempty"`
	Erase         *RpcErase `protobuf:"bytes,20,opt,name=erase,proto3,oneof" json:"erase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileRpcOptions) Reset() {
	*x = FileRpcOptions{}
	mi := &file_orm_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileRpcOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileRpcOptions) ProtoMessage() {}

func (x *FileRpcOptions) ProtoReflect() protoreflect.Message {
	mi := &file_orm_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileRpcOptions.ProtoReflect.Descriptor instead.
func (*FileRpcOptions) Descriptor() ([]byte, []int) {
	return file_orm_proto_rawDescGZIP(), []int{8}
}

func (x *FileRpcOptions) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *FileRpcOptions) GetCrud() bool {
	if x != nil {
		return x.Crud
	}
	return false
}

func (x *FileRpcOptions) GetAdd() *RpcAdd {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *FileRpcOptions) GetGet() *RpcGet {
	if x != nil {
		return x.Get
	}
	return nil
}

func (x *FileRpcOptions) GetList() *RpcList {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *FileRpcOptions) GetPatch() *RpcPatch {
	if x != nil {
		return x.Patch
	}
	return nil
}

func (x *FileRpcOptions) GetErase() *RpcErase {
	if x != nil {
		return x.Erase
	}
	return nil
}

type RpcOptions struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Disabled *bool                  `protobuf:"varint,1,opt,name=disabled,proto3,oneof" json:"disabled,omitempty"`
	// Enables add, get, patch, and erase.
	Crud          *bool     `protobuf:"varint,2,opt,name=crud,proto3,oneof" json:"crud,omitempty"`
	Add           *RpcAdd   `protobuf:"bytes,16,opt,name=add,proto3,oneof" json:"add,omitempty"`
	Get           *RpcGet   `protobuf:"bytes,17,opt,name=get,proto3,oneof" json:"get,omitempty"`
	List          *RpcList  `protobuf:"bytes,18,opt,name=list,proto3,oneof" json:"list,omitempty"`
	Patch         *RpcPatch `protobuf:"bytes,19,opt,name=patch,proto3,oneof" json:"patch,omitempty"`
	Erase         *RpcErase `protobuf:"bytes,20,opt,name=erase,proto3,oneof" json:"erase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcOptions) Reset() {
	*x = RpcOptions{}
	mi := &file_orm_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcOptions) ProtoMessage() {}

func (x *RpcOptions) ProtoReflect() protoreflect.Message {
	mi := &file_orm_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcOptions.ProtoReflect.Descriptor instead.
func (*RpcOptions) Descriptor() ([]byte, []int) {
	return file_orm_proto_rawDescGZIP(), []int{9}
}

func (x *RpcOptions) GetDisabled() bool {
	if x != nil && x.Disabled != nil {
		return *x.Disabled
	}
	return false
}

func (x *RpcOptions) GetCrud() bool {
	if x != nil && x.Crud != nil {
		return *x.Crud
	}
	return false
}

func (x *RpcOptions) GetAdd() *RpcAdd {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *RpcOptions) GetGet() *RpcGet {
	if x != nil {
		return x.Get
	}
	return nil
}

func (x *RpcOptions) GetList() *RpcList {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *RpcOptions) GetPatch() *RpcPatch {
	if x != nil {
		return x.Patch
	}
	return nil
}

func (x *RpcOptions) GetErase() *RpcErase {
	if x != nil {
		return x.Erase
	}
	return nil
}

type RpcAdd struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disabled      bool                   `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcAdd) Reset() {
	*x = RpcAdd{}
	mi := &file_orm_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcAdd) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcAdd) ProtoMessage() {}

func (x *RpcAdd) ProtoReflect() protoreflect.Message {
	mi := &file_orm_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcAdd.ProtoReflect.Descriptor instead.
func (*RpcAdd) Descriptor() ([]byte, []int) {
	return file_orm_proto_rawDescGZIP(), []int{10}
}

func (x *RpcAdd) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type RpcGet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disabled      bool                   `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcGet) Reset() {
	*x = RpcGet{}
	mi := &file_orm_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcGet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcGet) ProtoMessage() {}

func (x *RpcGet) ProtoReflect() protoreflect.Message {
	mi := &file_orm_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcGet.ProtoReflect.Descriptor instead.
func (*RpcGet) Descriptor() ([]byte, []int) {
	return file_orm_proto_rawDescGZIP(), []int{11}
}

func (x *RpcGet) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type RpcList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disabled      bool                   `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcList) Reset() {
	*x = RpcList{}
	mi := &file_orm_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcList) ProtoMessage() {}

func (x *RpcList) ProtoReflect() protoreflect.Message {
	mi := &file_orm_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcList.ProtoReflect.Descriptor instead.
func (*RpcList) Descriptor() ([]byte, []int) {
	return file_orm_proto_rawDescGZIP(), []int{12}
}

func (x *RpcList) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type RpcPatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disabled      bool                   `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcPatch) Reset() {
	*x = RpcPatch{}
	mi := &file_orm_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcPatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcPatch) ProtoMessage() {}

func (x *RpcPatch) ProtoReflect() protoreflect.Message {
	mi := &file_orm_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcPatch.ProtoReflect.Descriptor instead.
func (*RpcPatch) Descriptor() ([]byte, []int) {
	return file_orm_proto_rawDescGZIP(), []int{13}
}

func (x *RpcPatch) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type RpcErase struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Disabled      bool                   `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RpcErase) Reset() {
	*x = RpcErase{}
	mi := &file_orm_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RpcErase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RpcErase) ProtoMessage() {}

func (x *RpcErase) ProtoReflect() protoreflect.Message {
	mi := &file_orm_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RpcErase.ProtoReflect.Descriptor instead.
func (*RpcErase) Descriptor() ([]byte, []int) {
	return file_orm_proto_rawDescGZIP(), []int{14}
}

func (x *RpcErase) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

type Index struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Disabled  bool                   `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Refs      []uint32               `protobuf:"varint,3,rep,packed,name=refs,proto3" json:"refs,omitempty"`
	Unique    bool                   `protobuf:"varint,6,opt,name=unique,proto3" json:"unique,omitempty"`
	Immutable bool                   `protobuf:"varint,8,opt,name=immutable,proto3" json:"immutable,omitempty"`
	// If the index is unique and this field is true,
	// the schema will be written as a unique index,
	// but it will not be treated as a key in the graph.
	// In other words, this index will be excluded
	// from messages like GetRequest.
	Hidden        bool `protobuf:"varint,9,opt,name=hidden,proto3" json:"hidden,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Index) Reset() {
	*x = Index{}
	mi := &file_orm_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Index) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Index) ProtoMessage() {}

func (x *Index) ProtoReflect() protoreflect.Message {
	mi := &file_orm_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Index.ProtoReflect.Descriptor instead.
func (*Index) Descriptor() ([]byte, []int) {
	return file_orm_proto_rawDescGZIP(), []int{15}
}

func (x *Index) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *Index) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Index) GetRefs() []uint32 {
	if x != nil {
		return x.Refs
	}
	return nil
}

func (x *Index) GetUnique() bool {
	if x != nil {
		return x.Unique
	}
	return false
}

func (x *Index) GetImmutable() bool {
	if x != nil {
		return x.Immutable
	}
	return false
}

func (x *Index) GetHidden() bool {
	if x != nil {
		return x.Hidden
	}
	return false
}

var file_orm_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*FileOptions)(nil),
		Field:         45000,
		Name:          "orm.all",
		Tag:           "bytes,45000,opt,name=all",
		Filename:      "orm.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         45001,
		Name:          "orm.message",
		Tag:           "bytes,45001,opt,name=message",
		Filename:      "orm.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*RpcOptions)(nil),
		Field:         45002,
		Name:          "orm.rpcs",
		Tag:           "bytes,45002,opt,name=rpcs",
		Filename:      "orm.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldOptions)(nil),
		Field:         45003,
		Name:          "orm.field",
		Tag:           "bytes,45003,opt,name=field",
		Filename:      "orm.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*EdgeOptions)(nil),
		Field:         45004,
		Name:          "orm.edge",
		Tag:           "bytes,45004,opt,name=edge",
		Filename:      "orm.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional orm.FileOptions all = 45000;
	E_All = &file_orm_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional orm.MessageOptions message = 45001;
	E_Message = &file_orm_proto_extTypes[1]
	// optional orm.RpcOptions rpcs = 45002;
	E_Rpcs = &file_orm_proto_extTypes[2]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional orm.FieldOptions field = 45003;
	E_Field = &file_orm_proto_extTypes[3]
	// optional orm.EdgeOptions edge = 45004;
	E_Edge = &file_orm_proto_extTypes[4]
)

var File_orm_proto protoreflect.FileDescriptor

const file_orm_proto_rawDesc = "" +
	"\n" +
	"\torm.proto\x12\x03orm\x1a google/protobuf/descriptor.proto\"k\n" +
	"\vFileOptions\x123\n" +
	"\bmessages\x18\x01 \x01(\v2\x17.orm.FileMessageOptionsR\bmessages\x12'\n" +
	"\x04rpcs\x18\x02 \x01(\v2\x13.orm.FileRpcOptionsR\x04rpcs\"0\n" +
	"\x12FileMessageOptions\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\"a\n" +
	"\x0eMessageOptions\x12\x1d\n" +
	"\aenabled\x18\x01 \x01(\bH\x00R\aenabled\x88\x01\x01\x12$\n" +
	"\aindexes\x18\x02 \x03(\v2\n" +
	".orm.IndexR\aindexesB\n" +
	"\n" +
	"\b_enabled\"\xf2\x01\n" +
	"\fFieldOptions\x12\x18\n" +
	"\aignored\x18\x01 \x01(\bR\aignored\x12\x1d\n" +
	"\x04type\x18\x02 \x01(\x0e2\t.orm.TypeR\x04type\x12\x10\n" +
	"\x03key\x18\x05 \x01(\bR\x03key\x12\x16\n" +
	"\x06unique\x18\x06 \x01(\bR\x06unique\x12\x1a\n" +
	"\bnullable\x18\a \x01(\bR\bnullable\x12\x1c\n" +
	"\timmutable\x18\b \x01(\bR\timmutable\x12\x1a\n" +
	"\bsupplied\x18\n" +
	" \x01(\bR\bsupplied\x12\x1d\n" +
	"\adefault\x18\t \x01(\tH\x00R\adefault\x88\x01\x01B\n" +
	"\n" +
	"\b_default\"\x9e\x01\n" +
	"\vEdgeOptions\x12\x18\n" +
	"\aignored\x18\x01 \x01(\bR\aignored\x12\x12\n" +
	"\x04bind\x18\x02 \x01(\x05R\x04bind\x12'\n" +
	"\x04from\x18\x03 \x01(\v2\x13.orm.BackRefOptionsR\x04from\x12\x1a\n" +
	"\bnullable\x18\a \x01(\bR\bnullable\x12\x1c\n" +
	"\timmutable\x18\b \x01(\bR\timmutable\"^\n" +
	"\x0eBackRefOptions\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x124\n" +
	"\avirtual\x18\x02 \x01(\v2\x1a.orm.VirtualBackRefOptionsR\avirtual\"}\n" +
	"\x15VirtualBackRefOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06shared\x18\x02 \x01(\bR\x06shared\x12\x1a\n" +
	"\bnullable\x18\a \x01(\bR\bnullable\x12\x1c\n" +
	"\timmutable\x18\b \x01(\bR\timmutable\"#\n" +
	"\rSelectOptions\x12\x12\n" +
	"\x04refs\x18\x02 \x03(\x05R\x04refs\"\xb0\x02\n" +
	"\x0eFileRpcOptions\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\x12\x12\n" +
	"\x04crud\x18\x02 \x01(\bR\x04crud\x12\"\n" +
	"\x03add\x18\x10 \x01(\v2\v.orm.RpcAddH\x00R\x03add\x88\x01\x01\x12\"\n" +
	"\x03get\x18\x11 \x01(\v2\v.orm.RpcGetH\x01R\x03get\x88\x01\x01\x12%\n" +
	"\x04list\x18\x12 \x01(\v2\f.orm.RpcListH\x02R\x04list\x88\x01\x01\x12(\n" +
	"\x05patch\x18\x13 \x01(\v2\r.orm.RpcPatchH\x03R\x05patch\x88\x01\x01\x12(\n" +
	"\x05erase\x18\x14 \x01(\v2\r.orm.RpcEraseH\x04R\x05erase\x88\x01\x01B\x06\n" +
	"\x04_addB\x06\n" +
	"\x04_getB\a\n" +
	"\x05_listB\b\n" +
	"\x06_patchB\b\n" +
	"\x06_erase\"\xcc\x02\n" +
	"\n" +
	"RpcOptions\x12\x1f\n" +
	"\bdisabled\x18\x01 \x01(\bH\x00R\bdisabled\x88\x01\x01\x12\x17\n" +
	"\x04crud\x18\x02 \x01(\bH\x01R\x04crud\x88\x01\x01\x12\"\n" +
	"\x03add\x18\x10 \x01(\v2\v.orm.RpcAddH\x02R\x03add\x88\x01\x01\x12\"\n" +
	"\x03get\x18\x11 \x01(\v2\v.orm.RpcGetH\x03R\x03get\x88\x01\x01\x12%\n" +
	"\x04list\x18\x12 \x01(\v2\f.orm.RpcListH\x04R\x04list\x88\x01\x01\x12(\n" +
	"\x05patch\x18\x13 \x01(\v2\r.orm.RpcPatchH\x05R\x05patch\x88\x01\x01\x12(\n" +
	"\x05erase\x18\x14 \x01(\v2\r.orm.RpcEraseH\x06R\x05erase\x88\x01\x01B\v\n" +
	"\t_disabledB\a\n" +
	"\x05_crudB\x06\n" +
	"\x04_addB\x06\n" +
	"\x04_getB\a\n" +
	"\x05_listB\b\n" +
	"\x06_patchB\b\n" +
	"\x06_erase\"$\n" +
	"\x06RpcAdd\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\"$\n" +
	"\x06RpcGet\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\"%\n" +
	"\aRpcList\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\"&\n" +
	"\bRpcPatch\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\"&\n" +
	"\bRpcErase\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\"\x99\x01\n" +
	"\x05Index\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04refs\x18\x03 \x03(\rR\x04refs\x12\x16\n" +
	"\x06unique\x18\x06 \x01(\bR\x06unique\x12\x1c\n" +
	"\timmutable\x18\b \x01(\bR\timmutable\x12\x16\n" +
	"\x06hidden\x18\t \x01(\bR\x06hidden*\x9a\x03\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tTYPE_BOOL\x10\b\x12\r\n" +
	"\tTYPE_ENUM\x10\x0e\x12\x0e\n" +
	"\n" +
	"TYPE_INT32\x10\x05\x12\x0f\n" +
	"\vTYPE_SINT32\x10\x11\x12\x0f\n" +
	"\vTYPE_UINT32\x10\r\x12\x0e\n" +
	"\n" +
	"TYPE_INT64\x10\x03\x12\x0f\n" +
	"\vTYPE_SINT64\x10\x12\x12\x0f\n" +
	"\vTYPE_UINT64\x10\x04\x12\x11\n" +
	"\rTYPE_SFIXED32\x10\x0f\x12\x10\n" +
	"\fTYPE_FIXED32\x10\a\x12\x0e\n" +
	"\n" +
	"TYPE_FLOAT\x10\x02\x12\x11\n" +
	"\rTYPE_SFIXED64\x10\x10\x12\x10\n" +
	"\fTYPE_FIXED64\x10\x06\x12\x0f\n" +
	"\vTYPE_DOUBLE\x10\x01\x12\x0f\n" +
	"\vTYPE_STRING\x10\t\x12\x0e\n" +
	"\n" +
	"TYPE_BYTES\x10\f\x12\x10\n" +
	"\fTYPE_MESSAGE\x10\v\x12\x0e\n" +
	"\n" +
	"TYPE_GROUP\x10\n" +
	"\x12\f\n" +
	"\bTYPE_INT\x10\x03\x12\r\n" +
	"\tTYPE_UINT\x10\x04\x12\r\n" +
	"\tTYPE_UUID\x10@\x12\r\n" +
	"\tTYPE_TIME\x10A\x12\r\n" +
	"\tTYPE_JSON\x10B\x1a\x02\x10\x01:B\n" +
	"\x03all\x12\x1c.google.protobuf.FileOptions\x18\xc8\xdf\x02 \x01(\v2\x10.orm.FileOptionsR\x03all:P\n" +
	"\amessage\x12\x1f.google.protobuf.MessageOptions\x18\xc9\xdf\x02 \x01(\v2\x13.orm.MessageOptionsR\amessage:F\n" +
	"\x04rpcs\x12\x1f.google.protobuf.MessageOptions\x18\xca\xdf\x02 \x01(\v2\x0f.orm.RpcOptionsR\x04rpcs:H\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xcb\xdf\x02 \x01(\v2\x11.orm.FieldOptionsR\x05field:E\n" +
	"\x04edge\x12\x1d.google.protobuf.FieldOptions\x18\xcc\xdf\x02 \x01(\v2\x10.orm.EdgeOptionsR\x04edgeB#Z!github.com/lesomnus/proto-orm;ormb\x06proto3"

var (
	file_orm_proto_rawDescOnce sync.Once
	file_orm_proto_rawDescData []byte
)

func file_orm_proto_rawDescGZIP() []byte {
	file_orm_proto_rawDescOnce.Do(func() {
		file_orm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orm_proto_rawDesc), len(file_orm_proto_rawDesc)))
	})
	return file_orm_proto_rawDescData
}

var file_orm_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_orm_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_orm_proto_goTypes = []any{
	(Type)(0),                           // 0: orm.Type
	(*FileOptions)(nil),                 // 1: orm.FileOptions
	(*FileMessageOptions)(nil),          // 2: orm.FileMessageOptions
	(*MessageOptions)(nil),              // 3: orm.MessageOptions
	(*FieldOptions)(nil),                // 4: orm.FieldOptions
	(*EdgeOptions)(nil),                 // 5: orm.EdgeOptions
	(*BackRefOptions)(nil),              // 6: orm.BackRefOptions
	(*VirtualBackRefOptions)(nil),       // 7: orm.VirtualBackRefOptions
	(*SelectOptions)(nil),               // 8: orm.SelectOptions
	(*FileRpcOptions)(nil),              // 9: orm.FileRpcOptions
	(*RpcOptions)(nil),                  // 10: orm.RpcOptions
	(*RpcAdd)(nil),                      // 11: orm.RpcAdd
	(*RpcGet)(nil),                      // 12: orm.RpcGet
	(*RpcList)(nil),                     // 13: orm.RpcList
	(*RpcPatch)(nil),                    // 14: orm.RpcPatch
	(*RpcErase)(nil),                    // 15: orm.RpcErase
	(*Index)(nil),                       // 16: orm.Index
	(*descriptorpb.FileOptions)(nil),    // 17: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 18: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 19: google.protobuf.FieldOptions
}
var file_orm_proto_depIdxs = []int32{
	2,  // 0: orm.FileOptions.messages:type_name -> orm.FileMessageOptions
	9,  // 1: orm.FileOptions.rpcs:type_name -> orm.FileRpcOptions
	16, // 2: orm.MessageOptions.indexes:type_name -> orm.Index
	0,  // 3: orm.FieldOptions.type:type_name -> orm.Type
	6,  // 4: orm.EdgeOptions.from:type_name -> orm.BackRefOptions
	7,  // 5: orm.BackRefOptions.virtual:type_name -> orm.VirtualBackRefOptions
	11, // 6: orm.FileRpcOptions.add:type_name -> orm.RpcAdd
	12, // 7: orm.FileRpcOptions.get:type_name -> orm.RpcGet
	13, // 8: orm.FileRpcOptions.list:type_name -> orm.RpcList
	14, // 9: orm.FileRpcOptions.patch:type_name -> orm.RpcPatch
	15, // 10: orm.FileRpcOptions.erase:type_name -> orm.RpcErase
	11, // 11: orm.RpcOptions.add:type_name -> orm.RpcAdd
	12, // 12: orm.RpcOptions.get:type_name -> orm.RpcGet
	13, // 13: orm.RpcOptions.list:type_name -> orm.RpcList
	14, // 14: orm.RpcOptions.patch:type_name -> orm.RpcPatch
	15, // 15: orm.RpcOptions.erase:type_name -> orm.RpcErase
	17, // 16: orm.all:extendee -> google.protobuf.FileOptions
	18, // 17: orm.message:extendee -> google.protobuf.MessageOptions
	18, // 18: orm.rpcs:extendee -> google.protobuf.MessageOptions
	19, // 19: orm.field:extendee -> google.protobuf.FieldOptions
	19, // 20: orm.edge:extendee -> google.protobuf.FieldOptions
	1,  // 21: orm.all:type_name -> orm.FileOptions
	3,  // 22: orm.message:type_name -> orm.MessageOptions
	10, // 23: orm.rpcs:type_name -> orm.RpcOptions
	4,  // 24: orm.field:type_name -> orm.FieldOptions
	5,  // 25: orm.edge:type_name -> orm.EdgeOptions
	26, // [26:26] is the sub-list for method output_type
	26, // [26:26] is the sub-list for method input_type
	21, // [21:26] is the sub-list for extension type_name
	16, // [16:21] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_orm_proto_init() }
func file_orm_proto_init() {
	if File_orm_proto != nil {
		return
	}
	file_orm_proto_msgTypes[2].OneofWrappers = []any{}
	file_orm_proto_msgTypes[3].OneofWrappers = []any{}
	file_orm_proto_msgTypes[8].OneofWrappers = []any{}
	file_orm_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orm_proto_rawDesc), len(file_orm_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_orm_proto_goTypes,
		DependencyIndexes: file_orm_proto_depIdxs,
		EnumInfos:         file_orm_proto_enumTypes,
		MessageInfos:      file_orm_proto_msgTypes,
		ExtensionInfos:    file_orm_proto_extTypes,
	}.Build()
	File_orm_proto = out.File
	file_orm_proto_goTypes = nil
	file_orm_proto_depIdxs = nil
}
