// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.0
// source: orm/patch.proto

package orm

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PatchOp int32

const (
	PatchOp_UNSPECIFIED PatchOp = 0
	PatchOp_ADD         PatchOp = 1
	PatchOp_ERASE       PatchOp = 2
	PatchOp_CLEAR       PatchOp = 3
)

// Enum value maps for PatchOp.
var (
	PatchOp_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "ADD",
		2: "ERASE",
		3: "CLEAR",
	}
	PatchOp_value = map[string]int32{
		"UNSPECIFIED": 0,
		"ADD":         1,
		"ERASE":       2,
		"CLEAR":       3,
	}
)

func (x PatchOp) Enum() *PatchOp {
	p := new(PatchOp)
	*p = x
	return p
}

func (x PatchOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PatchOp) Descriptor() protoreflect.EnumDescriptor {
	return file_orm_patch_proto_enumTypes[0].Descriptor()
}

func (PatchOp) Type() protoreflect.EnumType {
	return &file_orm_patch_proto_enumTypes[0]
}

func (x PatchOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PatchOp.Descriptor instead.
func (PatchOp) EnumDescriptor() ([]byte, []int) {
	return file_orm_patch_proto_rawDescGZIP(), []int{0}
}

var File_orm_patch_proto protoreflect.FileDescriptor

const file_orm_patch_proto_rawDesc = "" +
	"\n" +
	"\x0form/patch.proto\x12\x03orm*9\n" +
	"\aPatchOp\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\a\n" +
	"\x03ADD\x10\x01\x12\t\n" +
	"\x05ERASE\x10\x02\x12\t\n" +
	"\x05CLEAR\x10\x03B#Z!github.com/lesomnus/proto-orm;ormb\x06proto3"

var (
	file_orm_patch_proto_rawDescOnce sync.Once
	file_orm_patch_proto_rawDescData []byte
)

func file_orm_patch_proto_rawDescGZIP() []byte {
	file_orm_patch_proto_rawDescOnce.Do(func() {
		file_orm_patch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orm_patch_proto_rawDesc), len(file_orm_patch_proto_rawDesc)))
	})
	return file_orm_patch_proto_rawDescData
}

var file_orm_patch_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_orm_patch_proto_goTypes = []any{
	(PatchOp)(0), // 0: orm.PatchOp
}
var file_orm_patch_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orm_patch_proto_init() }
func file_orm_patch_proto_init() {
	if File_orm_patch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orm_patch_proto_rawDesc), len(file_orm_patch_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orm_patch_proto_goTypes,
		DependencyIndexes: file_orm_patch_proto_depIdxs,
		EnumInfos:         file_orm_patch_proto_enumTypes,
	}.Build()
	File_orm_patch_proto = out.File
	file_orm_patch_proto_goTypes = nil
	file_orm_patch_proto_depIdxs = nil
}
