package plugin

import (
	"bytes"
	"errors"
	"fmt"
	"path/filepath"
	"text/template"

	"github.com/go-openapi/inflect"
	"github.com/lesomnus/proto-orm/graph"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"
)

type Plugin struct {
	Graph  graph.Graph
	EntPkg protogen.GoImportPath
	Naming string
}

func NewPlugin() *Plugin {
	return &Plugin{
		Graph: graph.Graph{},
	}
}

func (p *Plugin) Run(plugin *protogen.Plugin) error {
	plugin.SupportedEditionsMinimum = descriptorpb.Edition_EDITION_PROTO3
	plugin.SupportedEditionsMaximum = descriptorpb.Edition_EDITION_PROTO3
	plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

	if p.EntPkg == "" {
		return errors.New(`"ent" option must be given`)
	}

	namer := template.New("naming")
	namer.Funcs(template.FuncMap{
		"kebab": func(v string) string {
			return inflect.Dasherize(v)
		},
		"snake": func(v string) string {
			return inflect.Underscore(v)
		},
	})
	if _, err := namer.Parse(p.Naming); err != nil {
		return fmt.Errorf(`invalid option value "naming=%s": %w`, p.Naming, err)
	}

	g, err := graph.NewGraph(plugin.Files)
	if err != nil {
		return fmt.Errorf("graph: %w", err)
	}

	type Pkg struct {
		d  string                // directory path where this package is
		i  protogen.GoImportPath // path to this package
		pb protogen.GoImportPath // path to package generated by protobuf

		// File under this package.
		// Key is file name, e.g. "foo.go".
		fs map[string]*protogen.GeneratedFile
	}

	errs := []error{}
	pkgs := map[string]Pkg{}

	// Generate gRPC server implementation for each entity.
	for _, e := range g {
		if !e.File.Generate {
			continue
		}

		d, n := filepath.Split(e.File.GeneratedFilenamePrefix)
		b := &bytes.Buffer{}
		if err := namer.Execute(b, struct {
			Entity string
			Name   string
		}{
			Entity: e.Name(),
			Name:   n,
		}); err != nil {
			return fmt.Errorf("%s: name a generated file: %w", e.File.GoPackageName, err)
		}

		filename := b.String()
		pd := filepath.Join(d, "bare")
		pf := filepath.Join(pd, filename)
		pi := e.File.GoImportPath + "/bare"

		pkg, ok := pkgs[pd]
		if !ok {
			pkg = Pkg{
				d:  pd,
				i:  pi,
				pb: e.File.GoImportPath,
				fs: map[string]*protogen.GeneratedFile{},
			}

			pkgs[pd] = pkg
		}

		f, ok := pkg.fs[filename]
		if !ok {
			f = plugin.NewGeneratedFile(pf, pi)
			p.printPrelude(f)

			pkg.fs[filename] = f
		}

		printer := Printer{
			EntPkg: p.EntPkg,
			PbPkg:  e.File.GoImportPath,
		}
		if err := printer.Print(g, e, f); err != nil {
			err = fmt.Errorf("print %s: %w", e.FullName(), err)
			errs = append(errs, err)
		}
	}

	// Generate common codes for entity package.
	for _, pkg := range pkgs {
		b := &bytes.Buffer{}
		if err := namer.Execute(b, struct {
			Entity string
			Name   string
		}{
			Entity: "misc",
			Name:   "misc",
		}); err != nil {
			return fmt.Errorf("name a file for common code: %w", err)
		}

		pf := filepath.Join(pkg.d, b.String())
		f := plugin.NewGeneratedFile(pf, pkg.i)
		p.printPrelude(f)

		printer := Printer{
			EntPkg: p.EntPkg,
			PbPkg:  pkg.pb,
		}
		t := printer.newTemplate(f)
		if err := t.ExecuteTemplate(f, "misc.go.tpl", nil); err != nil {
			err = fmt.Errorf(`print common code: %w`, err)
			errs = append(errs, err)
			continue
		}
	}

	if len(errs) > 0 {
		return errors.Join(errs...)
	}

	return nil
}

func (p *Plugin) printPrelude(f *protogen.GeneratedFile) {
	f.P(`// Code generated by "protoc-gen-orm-ent-grpc", DO NOT EDIT.`)
	f.P("")
	f.P("package bare")
	f.P("")
}
